### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [tauyoungsama/zsh-prompt#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I only add themes with a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

The plugin's name is very generic. Please consider renaming it to something descriptive, or even just name it after your github username.

Thanks!

**Comment by taumasyang** [comment]
Thank you for your appreciation! This prompt is just a toy and is similar to its reference. I do not consider it valuable enough to be recommended, though.

The project is unlicensed and anyone can use it freely.

**Comment by unixorn** [comment]
ok, thanks. You should make a license file saying that though :-)
